### ISSUE TITLE
Bring over the templating tasks from rake in FubuMVC

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/fubu#5]
I don't completely understand them yet, but I'm betting they're necessary

**Comment by jmarnold** [comment]
I'm betting they're not. Old artifacts from the old fubu new that I killed

**Comment by storyteller** [comment]
Aw, ok.
 Jeremy D. Miller
The Shade Tree Developer
jeremydmiller@yahoo.com

**Comment by jeremydmiller** [comment]
Big nevermind.
