### ISSUE TITLE
New "run" command

### ISSUE THREAD

**Issue by jeremydmiller** [FubuMvcArchive/fubu#8]
Build yet another command to open applications, but this time w/ Katana.

"run" -- in the solution, tries to find the IApplicationSource if it's unique.  If not unique, lists out everything that exists.  If none, says "none"

"run" -- in a project folder, only looks in the folder assembly.  Easy peasy

"run --application [application name]"

"run --folder [folder name]" -- could be an alias

"run --watched" -- this is the cool one.  
- Launches the browser, maybe w/ WebDriver, maybe using Process.Run()
- When an assembly file is changed, trash the AppDomain running the Fubu app and rebuild it.  Refresh the browser.
- If a config file changes, restart the fubu application within the AppDomain
- If a content file (view, asset, etc.) changes, refresh the browser

If we were to use WebDriver, refreshing the browser becomes easy, but the browser compatibility issues w/ WebDriver revisions is starting to scare me.  Maybe we could rig up something by injecting Javascript.

**Comment by KevM** [comment]
Sounds like the the goal of this command is to make the dev experience better so we don't have to constantly refresh the browser and restart the app or wonder if the app is restarted. This would be **great**.

#### WebDriver

Good news on the WebDriver front in that the API is now a [W3C working draft](http://www.w3.org/TR/2013/WD-webdriver-20130117/) This is the first step towards making support for it standard across browser. 

> Insert joke here about the lifecycle of W3C specification process

**Comment by smerrell** [comment]
:+1:

One thing I'd be curious about is how fast app restarts would be, especially when combined with a bunch of bottles.

**Comment by jeremydmiller** [comment]
This was done quite some time ago
